### ISSUE TITLE
pygame.error: mixer not initialized

### ISSUE THREAD

**Issue by iprathammishra** [MazenTayseer/Automated_Flappy_Bird#2]
Trouble initializing the mixer.

**Comment by MazenTayseer** [comment]
Can you provide the error?

**Comment by iprathammishra** [comment]
Problem in line 28:
BG_MUSIC = pygame.mixer.Sound('music/music.wav')
BG_MUSIC.play(loops=-1)

Error:
pygame.error: mixer not initialized

idk, i haven't checked the code locally in my machine. maybe it's just a codespace issue.

**Comment by MazenTayseer** [comment]
This isn't supposed to happen to happen, as `pygame.init()` initializes the mixer, Nonetheless, I added `pygame.mixer.initiliaze()` to help with this
